version: '3'
services:
  nginx:
    image: nginx:1.15.0-alpine
    ports:
      - ${VIRTUAL_PORT}:80
      - 443:443
    restart: always
    depends_on:
      - php
    env_file: .env
    volumes:
      - ./setting/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./setting/nginx/conf:/etc/nginx/conf/:ro
      - ./wordpress:/var/www/html:ro
    networks:
      - front
      - back

  php:
    build: ./docker/php
    ports:
      - 9000:9000
    restart: always
    environment:
      DATABASE_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - ./setting/php:/usr/local/etc/php:ro
      - ./wordpress:/var/www/html
    networks:
      - back

  mysql:
    image: mysql:5.7.22
    ports:
      - 3333:3306
    restart: always
    env_file: .env
    volumes:
      - ./db/local:/var/lib/mysql
      - ./db/initialize:/docker-entrypoint-initdb.d/initial.sql
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    links:
      - mysql
    ports:
      - 8888:80
    volumes:
      - "./phpmyadmin/sessions:/sessions"
    networks:
      - back

volumes:
  data-wp:
    # external:
    #   name: ${COMPOSE_PROJECT_NAME}-wp
  data-db:
    # external:
    #   name: ${COMPOSE_PROJECT_NAME}-db

networks:
  front:
    # external: true
  back: